version: "3.9"

services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  oracle_xe:
    image: gvenzl/oracle-xe:21.3.0
    platform: linux/amd64
    environment:
      ORACLE_PASSWORD: test
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1521:1521"
    volumes:
      - ./oracle_xe/init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s test/test@XEPDB1 || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 180s  # Увеличиваем время на инициализацию
    mem_limit: 3g  # Увеличиваем память для Oracle
    shm_size: 2g

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: abcde
    ports:
      - "8123:8123"  # HTTP порт
      - "9000:9000"  # Native порт
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse  # Персистентное хранилище
    mem_limit: 1g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  clickhouse_data: